services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - 5433:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./back/db/:/var/lib/postgresql/data/
  
  backend:
    image: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      ENVIRONMENT_FRONTEND: ${ENVIRONMENT_FRONTEND}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      TRUSTED_IP: ${TRUSTED_IP}
      CIFRA_SCRAPER_BASE_URL: ${CIFRA_SCRAPER_BASE_URL}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./back/:/app/

  frontend:
    image: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3001:3000
    restart: always
    volumes:
      - ./front/:/app/
