services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres2024
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mycifras
    volumes:
      - ./back/db/:/var/lib/postgresql/data/
  
  backend:
    image: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./back/:/app/

  frontend:
    image: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3001:3000
    restart: always
    volumes:
      - ./front/:/app/