-- AlterTable
ALTER TABLE "User" ADD COLUMN     "canAddSong" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "canSyncCifra" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isAdmin" BOOLEAN NOT NULL DEFAULT false;
